image: node:16
cache:
  paths:
    - node_modules/

before_script:
  - yarn install

pages:
  stage: deploy
  script:
    - yarn generate
    - yarn generate:storybook
    - rm -rf public/storybook
    - mv storybook public/
  tags:
    - build
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
