image: node:16
cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run generate
    - npm run start
  tags:
    - build
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
